version: '3'
networks:
  db:
  web:
services:
  mongodb:
    restart: always
    image: mongo:latest
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb/plutus:/data/db
    networks:
      - db
  plutus-service:
    restart: always
    build: ./plutus-service
    image: plutus-service
    environment:
      - DB=mongodb
      - PORT=5000
      - SECRET={yourJwtSecretKey}
      - SECRETKEY={yourCriptoSecretKey}
    networks:
      - db
      - web
    ports:
      - 5000:5000
  plutus-app:
    build: ./plutus-app
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - plutus-service
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
