version: '3'
networks:
  db:
  web:
services:
  mongodb:
    restart: always
    image: mongo:latest
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb/plutus:/data/db
    networks:
      - db
  plutus-service:
    restart: always
    build: ./plutus-service
    image: plutus-service
    environment:
      - DB=mongodb
      - PORT=5000
      - SECRET={yourJwtSecretKey}
      - SECRETKEY={yourCriptoSecretKey}
    networks:
      - db
      - web
    ports:
      - 5000:5000
  frontend:
    build: ./plutus-app
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - plutus-service
    ports:
      - 80:80